name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 9.0.1
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-
      - run: cabal test --test-show-details direct
      - run: cabal check
